services:
    _defaults:
        public: true

    PimcoreS3Bundle\Service\CloudFrontService:
        arguments:
            - '@pimcore_s3.client.cloudfront'
            - '%pimcore_s3.cloudfront.id%'

    PimcoreS3Bundle\EventListener\AssetListener:
        arguments:
            - '@PimcoreS3Bundle\Service\CloudFrontService'
            - '@pimcore_s3.client.cloudfront'
            - '%pimcore_s3.enable_cli_thumbnail_path_check%'
            - '%pimcore_s3.region%'
            - '%pimcore_s3.credentials.access_key_id%'
            - '%pimcore_s3.credentials.secret_access_key%'
            - '%pimcore_s3.bucket_name%'
            - '%pimcore_s3.base_url%'
            - '%pimcore_s3.pimcore_directory.tmp%'
            - '%pimcore_s3.pimcore_directory.asset%'
            - '%pimcore_s3.cloudfront.enabled%'
            - '%pimcore_s3.cloudfront.id%'
            - '%pimcore_s3.cdn.enabled%'
            - '%pimcore_s3.cdn.domain%'
        tags:
            - { name: kernel.event_subscriber }

    pimcore_s3.client.cloudfront:
        class: PimcoreS3Bundle\Client\CloudFrontClient
        arguments:
            - '%pimcore_s3.cloudfront.client.version%'
            - '%pimcore_s3.region%'
            - '%pimcore_s3.credentials.access_key_id%'
            - '%pimcore_s3.credentials.secret_access_key%'
