name: reviewdog

on:
    - pull_request

jobs:
    misspell:
        name: runner / misspell
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code.
                uses: actions/checkout@v1
            -   name: misspell
                uses: reviewdog/action-misspell@v1
                with:
                    level: 'error'
                    locale: 'US'
                    path: './src'
                    exclude: './Resources/google/*'

    phpmd-linter:
        name: PHPMD
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code into the workspace
                uses: actions/checkout@v2
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies for PHPMD
                uses: php-actions/composer@v5
                with:
                    php_version: 8
                    version: 2
                    command: install --no-scripts --ignore-platform-reqs
            -   name: Run php check code with reviewdog
                uses: GeneaLabs/action-reviewdog-phpmd@1.0.0
                with:
                    github_token: '${{ github.token }}'
                    level: 'error'
                    reporter: 'github-pr-check'
                    standard: './phpmd.xml'
                    target_directory: 'src'

    phpstan-linter:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code into the workspace
                uses: actions/checkout@v2
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies for PHPMD
                uses: php-actions/composer@v5
                with:
                    php_version: 8
                    version: 2
                    command: install --no-scripts --ignore-platform-reqs
            -   name: Run php check code with reviewdog
                uses: GeneaLabs/action-reviewdog-phpstan@1.0.0
                with:
                    github_token: '${{ github.token }}'
                    level: 'error'
                    reporter: 'github-pr-check'
                    target_directory: 'src'